"""Currency table - added autoincrement to id column

Revision ID: 2c354c71fd2a
Revises: c8d54feb92d2
Create Date: 2023-11-01 15:15:22.841852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c354c71fd2a'
down_revision: Union[str, None] = 'c8d54feb92d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'currency', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency', type_='unique')
    # ### end Alembic commands ###
