"""Added currency_requests table

Revision ID: d318e3b17154
Revises: 7f4361d919c3
Create Date: 2023-10-27 18:02:09.789731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd318e3b17154'
down_revision: Union[str, None] = '7f4361d919c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('requested_banks', sa.ARRAY(sa.String(), dimensions=30), nullable=True),
    sa.Column('request_source', sa.String(length=50), nullable=True),
    sa.Column('currency_data', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_requests')
    # ### end Alembic commands ###
